package uz.pdp.inventorymanagementsystem.enums

enum class ErrorCodes(val code: Long) {

    VALIDATION_ERROR(100),

    BRAND_NOT_FOUND(206),
    BRAND_ALREADY_EXISTS(207),

    TAG_NOT_FOUND(208),
    TAG_ALREADY_EXISTS(209),

    UOM_NOT_FOUND(210),
    UOM_ALREADY_EXISTS(211),

    WAREHOUSE_NOT_FOUND(204),

    CATEGORY_NOT_FOUND(215),

    SUPPLIER_NOT_FOUND(212),

    EMPLOYEE_NOT_FOUND(201),

    ROLE_NOT_FOUND(213),
    PERMISSION_NOT_FOUND(214),

    PRODUCT_NOT_FOUND(200),

    FILE_NOT_FOUND(205),

    CATEGORY_ALREADY_EXISTS(203),
}
